### ISSUE TITLE
Investigate usage of Google Forms

### ISSUE THREAD

**Issue by m00lecule** [AGH-IOIO/NotiForms#5]
- how to retrive data from survey
- how to list current surveys

**Comment by m00lecule** [comment]
share results of survey - https://www.youtube.com/watch?v=2dUQpW7_G9U

**Comment by m00lecule** [comment]
limit of responses - https://www.youtube.com/watch?v=fHY8uI2VFP4

**Comment by pwrobel5** [comment]
list owned surveys - https://stackoverflow.com/questions/38601016/how-do-you-programmatically-get-a-list-of-google-forms-with-ids-using-google-f?rq=1

**Comment by pwrobel5** [comment]
https://pbpython.com/pandas-google-forms-part1.html
https://pbpython.com/pandas-google-forms-part2.html

it looks like, it's no way to get response data directly, without convertion of survey results to Google Spreadsheet

**Comment by j-adamczyk** [comment]
Summary: overall and individual, various options available: 
https://www.youtube.com/watch?v=LxlfPLPI0wM

Automatically save results to file:
https://www.youtube.com/watch?v=5f96ZGHrXi8

**Comment by m00lecule** [comment]
google add-ons - https://developers.google.com/gsuite/add-ons/editors/forms

https://www.youtube.com/watch?v=CLjXEdKbqqs

**Comment by j-adamczyk** [comment]
After the above research we had a discussion and saw 2 possibilites:
A) create a Google Forms add-on with Google modified JS
B) create everything ourselves from scratch

We voted on option B.
